### ISSUE TITLE
Phrase incomplète

### ISSUE THREAD

**Issue by gyoo18** [gyoo18/Prog1_jeu#2]
```
    # TODO Compléter la phrase
    print("Chef Alchimiste : « Vous avez maintenant une très grande expérience de combat réel, vous êtes de ce fait suffisamment près pour utiliser le nouveau ... »")
```
Dans dialogue.py

J'ai copié le dialogue, mais la capture d'écran l'a coupé.

**Comment by mario0393** [comment]
juste une grande ébauche du code du système de communication du jeu.
def zone_1(): 
      print("  ")
      print("  ")
      success  = combat_simple()
      if success :
         print(" ")
         return "success"
      else:
         print(" ")
         return "failure"
def zone_2:
        print(" ")
        print(" ")
        print(" ")
        print(" ")
        input(" ")
        success = combat_complexe()
        if success:
            print(" ")
            input(" ")
            if choix == "1"
                print(" ")
             else:
                print(" ")
              return "success"
       else: 
              print(" ")
              return"failure"
def zone_3(fin_zone_2):
        print(" ")
        print(" ")
        if fin_zone_2 == "fuir"
             print(" ")
        else:
             print(" ")
          combat = combat_final()
          if  success:
               print(" ")
               choix = input(" ")
           return choix
           else:
                 print(" ")
                 return "failure"
def  combat_simple():
      return input(" ")
def combat_complexe():
       return input(" ")
def combat_final()
       return input(" ")
def jeu_principal():
       print(" ")
       resultat_zone_1 = zone_1()
       if resultat_zone_1 == "failure":
           print(" ")
           return
        resultat_zone_2 = zone_2()
        if resultat_zone_2 = "failure":
            print(" ")
            return
            resultat_zone_3 = zone_3(resultat_zone_2)
        if resultat_zone_3 == "failure":
            print(" ")
         elif resultat_zone_3 == "1":
             print(" ")
         elif resultat_zone_3 == "2":
              print(" ")
         elif resultat_zone_3 == 3:
              print(" ")

**Comment by gyoo18** [comment]
Ce problème n'est plus à jour.
